### ISSUE TITLE
SearchPage 로직정리하기 

### ISSUE THREAD

**Issue by SoYoung210** [YAPP13-4/semi-basement#119]
## Description
함수형 프로그래밍을 생각해보며 컴포넌트내에서 로직을 짜보았습니다. 
하지만 **이렇게 짜도 되나...** 라는 생각이 들어, @eunjeongsong  @livelikeabel 두분을 assign 했습니다. 
PR 로도 올라갈 예정이긴 하지만, #109 PR 은 양이좀 많을것 같아서 개별 리뷰가 힘들것 같습니다.
그래서 이렇게 따로 이슈로..

### 개별 설명 
1. `selectedResult` 는 아래 화면에서 `검색 결과 분류` 옵션을 저장하는 state 입니다. 
> 하위 컴포넌트인 **NavBar** 에서 handleShowResultChange 함수를 실행합니다.

2. seperateResult 는 함수형 프로그래밍 책에 나왔던 `map` 함수를 똑같이 구현한 것입니다. 
> 이 함수는 isValidValue의 두 번째 인자로 들어갑니다. 
> isValidValue 에서는, 첫 번째 인자의 값이 유효하다면, 두 번째 인자를 실행합니다. (validAction, 여기선 함수를 넘기니 **실행** 이라고 표현하겠습니다. ) 

3. filterResult 역시 함수형 프로그래밍 책에 나왔던 `filter` 함수를 똑같이 구현한 것입니다. 
> this.state.selectedResult 가 "All" 이 아닐시에 , 분류를 위한 목적으로 사용합니다. 

```jsx
          this.state.selectedResult === "All"
            ? res => res
            : res => res.matches[0].key === this.state.selectedResult
```
`selectedResult` 가  All 이라면, 전체 res를 넘겨주고, 아니라면 필터 옵션을 만들어 줍니다. 

### 전체적인 Code 

```jsx
  state = {
    term: "",
    research: false, //SearchResult에서 재검색 하는지 검사할 state
    selectedResult: "All"
  }
  onInputChange = term => {
    this.setState(() => {
      return {
        term: term,
        research: true
      }
    })
  }
  handleShowResultChange = option => {
    this.setState(prevState => ({
      ...prevState,
      selectedResult: option
    }))
  }
  handleSubmit = e => {
    e.preventDefault()
    this.props.searchMusicRequest(this.state.term)
  }
  componentDidMount() {
    this.props.loadKeywordMusic(this.props.match.params.keyword)
  }
  seperateResult = (list, iteratee) => {
    let seperatedList = []

    for (let i = 0; i < list.length; i++) {
      seperatedList.push(iteratee(list[i]))
    }
    return seperatedList
  }
  filterResult = (list, predicate) => {
    let newList = []
    for (let i = 0; i < list.length; i++) {
      if (predicate(list[i])) newList.push(list[i])
    }
    return newList
  }
  isValidValue = (data, validAction, noValidACtion) => {
    return data ? validAction : noValidACtion
  }
  render() {
    const matchResult = this.props.searchResult
      ? Object.values(this.props.searchResult)
      : null

    const matchResultItem = this.isValidValue(
      matchResult,
      this.seperateResult(
        this.filterResult(
          matchResult,
          this.state.selectedResult === "All"
            ? res => res
            : res => res.matches[0].key === this.state.selectedResult
        ),
        res => res.item
      ),
      ""
    )
{/* 이하 생략 */}
}
```
리뷰해주시면 감사합니다 ❤️ 😄 ❤️ 

### source code 위치 
[109-SearchResult-index](https://github.com/YAPP13-4/semi-basement/blob/front/109-PandF/front/src/App/pages/SearchResult/index.js)

**Comment by SoYoung210** [comment]
## searchPage 기능 이슈 
- [ ] 처음 검색 후, 새로 고침 시 데이터 날라감. (왜지.. )

**Comment by livelikeabel** [comment]
오오 일단 적용해서 하신것 굳굳!
근데 책에서는 설명을 위해 처음부터 구현을 한거라서, 우리는 굳이 만들어서 안쓰고,  filter, map 함수와 같은것을 쓰는게 아마 더 낫지 않을까요..? 저희가 js로 구현을 하는것보다, js메서드는 c로 짜여져 있어서 성능면에서도 더 나을거 같고, 코드도 덜 작성할 수 있는거 같아요! ㅎㅎ
```js
const matchResultItem = this.isValidValue(
      matchResult,
      this.seperateResult(
        this.filterResult(
          matchResult,
          this.state.selectedResult === "All"
            ? res => res
            : res => res.matches[0].key === this.state.selectedResult
        ),
        res => res.item
      ),
```
책에서는 학습을 위해 이렇게 코드를 작성 했었는데, 저는 이게 가독성 측면에서 좋지 않다고 생각했었어요. 한단계 더 나아가서,
이 부분을 matchResult.filter(v=> something ).map(v => something) 
요렇게 `.` 체이닝으로 하면, 읽기에도 훨씬 수월하지 않을까 싶습니다 ㅎㅎ

만약 공부했던 함수형 프로그래밍을 적용해서 하고 싶은거라면,(저는 적용하면서 진짜 자신의 지식이 된다고 생각해서 완전 좋다고 생각합니다!) 결국 `seperateResult`는 map이고,  `filterResult`는 filter함수이니까(iteratee 와 prediate에 의해 어떤조건으로 filter하고, map하는건지 결정 되는거니까요), 이름을 map. filter로 만들고 util로 빼셔서 재사용 하시면서 쓰면 되지 않을까 싶어요 ㅎㅎ

이거 짜시면서 함수형 프로그래밍이 좀 더 익숙해 지셨을거 같네요! ㅋㅋ
이번에는 이 코드를 줄여보면 좋을거 같아여 ㅎㅎ
