### ISSUE TITLE
eslintrc를 추가하는 것이 어떨까요?

### ISSUE THREAD

**Issue by nayunhwan** [YAPP13-4/semi-basement#125]
현재 `eslintrc`가 파일로 지정되어있지 않아, 기존에 다른 코드 convention이 지정되어있는 에디터에서 코드를 수정할 때 코드 convention이 깨지게 됩니다.

`eslint` + `prittier의 eslint integration option` 조합으로 가는 것이 좀 더 협업할 때 좋을 것 같습니다.

convention 정의에 쟁점이 있을 경우
[Airbnb의 컨벤션 레퍼런스](https://github.com/airbnb/javascript)를 참고하시면 좋을 것 같습니다.

**Comment by SoYoung210** [comment]
이슈 감사합니다, 개발자간의 회의 후 반영 예정입니다.
