### ISSUE TITLE
Redux-logger 설치하는 것은 어떨까요?

### ISSUE THREAD

**Issue by nayunhwan** [YAPP13-4/semi-basement#126]
Redux의 Action을 효율적으로 logging하기 위해서 Redux-Logger 설치를 추천합니다.

```js
import { createLogger } from "redux-logger";
import createSagaMiddleware from "redux-saga";

const sagaMiddleware = createSagaMiddleware();
const logger = createLogger();

const middlewares = [];

middlewares.push(sagaMiddleware);

// Production에서는 Logger가 추가되지 않도록 함
if (process.env.NODE_ENV !== "production") {
  middlewares.push(logger);
}

const store = createStore(rootReducer, applyMiddleware(...middlewares));
```

`NODE_ENV`에서 Production일 경우에는, logger를 추가하지 않도록 예외처리 해주길 바랍니다. :)

**Comment by SoYoung210** [comment]
상세한 코드까지 적어주셔서 감사합니다.  :) 
현재 `Redux Dev Tool` 을 사용하고 있어, 아직 도입 하지는 않았지만 충분히 팀원들과 이야기 해볼만한 점이라고 생각합니다. 결정된 후 `close` 하겠습니다.

**Comment by SoYoung210** [comment]
Redux Dev Tool 을 사용하고 있어 redux-logger 설치에 대한 needs 는 없는 쪽으로 결론 났습니다.
이슈 감사드리며, 언제든 다양한 주제로 repo에 놀러와주세요! 
PR 도 환영입니다 😃
