### ISSUE TITLE
Component Test 

### ISSUE THREAD

**Issue by SoYoung210** [YAPP13-4/semi-basement#134]

**Comment by SoYoung210** [comment]
[어려움1](https://stackoverflow.com/questions/36211739/invariant-violation-could-not-find-store-in-either-the-context-or-props-of-c)

**Comment by SoYoung210** [comment]
## Description
테스트 환경은 무조건 **맞춰줘야 한다.**
`export default connect(..)(App)` 이런 식으로 되어있는 것은 결국 Store와 연결된 채 **default export ** 되었다는 것이다. 

테스트 코드에서 Store 없이 테스트 할수 없다.

1. mockStore를 생성한다 (redux-mock-store)
2. connect 된채로 export하지말고 정말 컴포넌트만 Export 해서 테스트. 

2번으로커밋. 아래 커밋이 예시.  

> 아직 snapshot test에 대한 이해가 조금더 필요하다.

**Comment by SoYoung210** [comment]
https://hackernoon.com/testing-react-components-with-jest-and-enzyme-41d592c174f

**Comment by SoYoung210** [comment]
## Stateless Component Test : 
`Presentation Component` 에서 테스트 해야할 것은 결국 **어떻게 보여지느냐.** 이다. 
그렇다면 중요한 것은 ,

1. style 이 잘 적용 되는가 ? 
- 일일히 class명을 하나하나 테스트 할 필요는 없고, root div의 class Name 만 체크하면 된다. 너무 불필요하게 체크하면 괜히 디자인 하나 수정했는데 테스트가 우르르 깨지는 상황만 발생한다. 
2. 이벤트 잘 발생하는가?
- Presentation Component에 이벤트 걸어두면, 결국 얘가 **잘 동작하면** 된다.  
ArtWorkPlay.js 에서는 `onClickPlay` 를 넘겨주는데, mock 함수로 만든 jest.fn() 이 동작하는가만 보면된다.  
**이 함수로 어떤 동작이 일어나는가는 또 별개의 테스트에서 작성**

**Comment by SoYoung210** [comment]
Jest 는 버전 말썽꾸러기... 23 잘동작

**Comment by JaeYeopHan** [comment]
@SoYoung210  너무 어려운 질문이... 저도 하나 하나 공부해나가는 단계라서 아는 만큼 답변을 드려보겠습니다.

# Answer

> 실제 코드와 의존성을 낮춘다는 것은 무엇일까? 테스트 코드란, 실제 코드를 테스트 하는 것인데 의존성은 당연한것이 아닌가? 어느 수준까지 작성하는 것이 좋은가?

테스트 코드란 작성된 production 코드를 테스트하는 것이기 때문에 말씀하신대로 의존성을 가질 수 밖에 없습니다. 하지만 요구사항의 변경 또는 다른 요소로 인해 production 코드가 변경될 경우 테스트 코드도 많은 부분이 변경되어야 할텐데, 이런 부분을 최소화 할 수 있도록 의존성을 **'낮추는'** 방향으로 테스트 코드를 작성합니다.

자연스럽게 어느 **수준**까지 테스트 코드를 작성해야 하는가 고민하게 됩니다. '내가 작성한 A라는 부분이 다른 사람에 의해 변경되었을 때 비즈니스 로직에 영향이 가는가'를 기준으로 작성할 수 있습니다. 다른 사람이 내가 작성한 코드를 편안한 마음을 갖고 수정할 수 있도록 테스트 코드를 통해 알려준다는 마음으로 테스트 코드를 작성할 수 있을 것 같습니다.

## CASE

이 추상적인 '수준'이란 것은 경험에서 습득하거나 잘 작성된 테스트 코드를 모방하면서 배울 수 있을 것 같습니다. 저도 아직 잘 모르는데요, 제 경험에 기반하여 세 가지 다른 case 예로 설명해보려 합니다.

### Util function test

가장 쉬운 테스트가 되겠습니다.

보통 `utils` 디렉토리에 위치하는 `function`들은 여러 범용성에 맞게 테스트되어야 합니다. 그래서 오히려 production code 보다 테스트 코드가 더 많을수도 있습니다. 배열과 관련된 간단한 util을 하나 만들어도, `null` 또는 `undefined`로 인자가 넘어갈 경우, 배열의 길이가 1개일 경우, 일반적인 상황 등등에 대해 테스트 코드를 작성하게 됩니다.

다른 이외의 **상황**들과 dependency가 전혀 없기 때문에 테스트 코드를 작성하는게 쉽습니다.

### Store test

- action이 제대로 생성되는지 테스트
- reducer가 상태를 알맞게 수정하는지 테스트
- 그 외 사용하고 있는 redux-util들이 제대로 동작하는지 테스트
  - saga, reselect 등의 라이브러리들은 각자의 라이브러리를 사용할 때 어떻게 테스트를 작성해야 하는가에 대한 내용을 포함하고 있어서 참고하시면 될 것 같습니다.

### Component UI test

말씀하신 `어느 정도 수준까지 테스트해야 하는가`가 제일 어려운 테스트가 컴포넌트 테스트일 것 같습니다. React에서 주로 사용되는 패턴으로 다음 두 컴포넌트의 역할이 제대로 정의되어 있고 분리가 잘 되어있다면 테스트를 작성하기 수월해집니다.

#### Dumb component (|| Presentational Component || Stateless Component)

상태가 없는 컴포넌트의 경우 Shallow mount를 통해서 해당 컴포넌트가 **내가 의도한대로** 렌더링되는지 파악해야 하는데 이게 쉽지 않습니다.

- props에 따라 렌더링이 달라지는 경우 해당 부분을 테스트
  - 특징이 되는 요소로 테스트 (root element의 클래스, 특정 element의 length 등)
- 특정 element에 등록된 이벤트가 trigger 시 의도한 function이 호출되는지 테스트
  - 의도한 function은 실제 function이 아니어도 됩니다. 이 실제 function은 별도로 테스트하여 컴포넌트 테스트와 분리해야 나중에 production 코드의 변경에 따라 수정되어야 하는 테스트 코드의 양이 줄어들게 됩니다.
- 스타일이 제대로 적용되었는지 테스트
  - 이 부분은 어쩔 수 없이 눈으로 확인해야부분이라 테스트 자동화가 어렵습니다. 다만 root element에 적용되는 클래스 이름으로 파악이 가능하다는 가정하에 진행할 수 있습니다. 모든 엘리먼트에 올바른 클래스가 들어가 있는지 파악할 수도 있지만 이는 디자인 변경에 따라 테스트 코드가 너무 많이 변경되어야 하므로 지양합니다.

#### Smart Component (|| Container Component)

- mockStore를 주입하고 그에 따라 props, state가 제대로 전달되는지 파악합니다.
- 특정 함수에 의해 action이 dispatch 된다면 해당 부분을 확인합니다.

## 의존성을 줄인다는 것

- production 코드와의 의존성은 최소화 / 테스트 코드간의 의존성은 없도록
  - 특정 테스트 코드가 다른 테스트 코드에 영향을 미치는 일은 없도록 합니다. 이를 위해 테스트 라이브러리에서는 `beforeEach` 등의 hook API를 제공합니다.
- api 호출과 관련된 로직은 `(mockData) => Promise.resolve(mockData)`이런 식으로 실제 API 호출을 하지 않고 mocking으로 처리.
  - 실제 api 호출이 포함된 테스트는 e2e 테스트에서 진행
- localStorage에 접근하는 코드의 경우 localStorage에 접근하는 util을 만들어 테스트 수행

```js
// Bad
function getItemFromLocalStorage(key) {
  const rawData = window.localStorage(key)

  return JSON.parse(rawData);
}

// Good
function getItemFrom(storage, key) {
  const rawData = storage(key)

  return JSON.parse(rawData);
}

const getItemFromLocalStorage = _.partial(window.localStorage, getItemFrom)
```

`getItemFromLocalStorage`라는 util function은 함수 내부에서 `window`를 참조하고 있기 때문에 node 환경인 테스트에서는 테스트가 힘듭니다. 이런 이유로 `getItemFrom`이라는 function으로 분리 후 localStorage와 격리된 상황에서 테스트를 진행할 수 있습니다.


> 벤치마크할 좋은 오픈소스 테스트 코드를 참고해볼까 ..? 그럼 무엇.. ?

1. https://github.com/WordPress/gutenberg
2. https://github.com/facebook/draft-js

> Front에서도 TDD 가 가능할까 ?

가능할거라 생각은 하지만 저도 안해봤습니다 :)
