### ISSUE TITLE
나중에 디자인 적으로 @Dironic 이야기 해볼사항

### ISSUE THREAD

**Issue by SoYoung210** [YAPP13-4/semi-basement#149]
나중에 디자인 적으로 @Dironic 이야기 해볼사항

_Originally posted by @SoYoung210 in https://github.com/YAPP13-4/semi-basement/pull/147_

**Comment by eunjeongsong** [comment]
선택된 음악이 없는경우 우측 MyPlayer 디자인 필요

**Comment by eunjeongsong** [comment]
#143 이슈와 동일

**Comment by SoYoung210** [comment]
중복 이슈이므로 Close하겠습니다.
