### ISSUE TITLE
music 리스트 생성

### ISSUE THREAD

**Issue by SkynI25** [YAPP13-4/semi-basement#32]

**Comment by SkynI25** [comment]
soundcloud api 와 연동해서 데이터를 가져오는 부분을 어떻게 해야할까..
이 부분을 해결해야 차트중 최근 목록 불러 오는 것도 구현할 수 있을텐데..

**Comment by SoYoung210** [comment]
@SkynI25 정확히 어떤 목적을 위해 데이터를 가져 와야 한다고 하시는건가요 ? 
음.. sc api 연동 코드는 아래와 같습니다. 

```jsx
//ApiConstants.js
const API_HOSTNAME = '//api.soundcloud.com';
export const CLIENT_ID = ''; //key 내용 삭제 (필요하시면 슬랙으로 물어봐주세요.)

const constructUrl = url => `${API_HOSTNAME}${url}${url.indexOf('?') === -1 ? '?' : '&'}client_id=${CLIENT_ID}`;
export const resolveUrl = songUrl => `${API_HOSTNAME}/resolve.json?url=${songUrl}&client_id=${CLIENT_ID}`
export const SONG_URL = constructUrl('/tracks/:id');

//Home/index.js
  _requestId = () => {
    SONG_URL_LIST.map( (url)=> {
      return axios.get(resolveUrl(url))
            .then(response => {
              this.setState({
                songInfos: this.state.songInfos.concat(response.data)
              }) 
            })
    })
  }

  _rederDiscover = () => {
    const songs = this.state.songInfos.map((songInfo, index) => {
      return <ArtworkPlay key={index}
                          singerName= {songInfo.user.permalink}
                          title = {songInfo.title}
                          artwork = {songInfo.artwork_url}
                          songId = {songInfo.id}
                          
              />
    })
```
_requestId 에서 axios.get 이용해서 ajax 콜 합니다. (sc docs읽어보니 resolve url같은 형식으로 하라고 해서 변한해서 넣어준거에요.) 

전 url 6개로 가지고 하고 있어서 
![image](https://user-images.githubusercontent.com/18658235/45895087-34874c80-be0b-11e8-8c74-e073b3984824.png)

ajax콜해서 받아오는 데이터를 배열로 만들어준 부분이 

```jsx
              this.setState({
                songInfos: this.state.songInfos.concat(response.data)
              }) 
```

이 부분입니다.

**Comment by SoYoung210** [comment]
@SkynI25 BE 단에서 ajax 요청의 응답결과로 artwork_url이나 stream_url 을 가지고 있을 필요는 없다고 생각합니다. 
soundcloud의 url은 바뀌지 않지만, 원곡자가 thumbnail을 바꾸거나 연동되어있는 mp3파일을 바뀔경우 `artwork_url` 이나 `steam_url` 이 바뀌기 때문입니다.
Client단에서 처리할시에 로딩시간이 있는 이슈가 있지만, 나중에 코드개선이나 Landing 모션을 넣는것으로 대체할까 생각중이었습니다. 

다르게 생각하고 계시면 코멘트 남겨주세요.

**Comment by SoYoung210** [comment]
정확히 DB에 어떤 값을 넣고 싶으신 건지, 어떤 데이터가 필요한지, 음.. 위의 댓글로 전 제 생각을 말씀드렸는데 혹시 soundcloud와 연동된 데이터가 필요하다고 생각되시면 왜 필요한지 말씀해주시면 답변 달아두겠습니다.

**Comment by SkynI25** [comment]
DB에는 작곡가의 이름, 음악이 등록된 시기, 재생 시간, 이름, 이미지, 해시태그 등의 정보가 저장이 되어야합니다. 필요한 이유는 등록된 시기 데이터를 통해서 최근 곡 목록을 디비에서 가져와 전달할 수 있기 때문입니다. 알려주신 정보를 토대로 백엔드단에서 url로부터 정보를 추출하는 방법을 찾아보겠습니다 ㅎㅎ

**Comment by boribap** [comment]
DB에 넣을 수 있는 값 1차적으로 삽입 완료 

해결해야할 사항 
1. like_count 값은 따로 사운드클라우드 url에서 받아오는게 아니므로 삽입 안함
2. hashtag값 - 지금은 hashtag_1에 모두 저장되는데, hashtag_1,2,3에 나누어서 저장하도록 변경해야함

**Comment by boribap** [comment]
해시태그 값 제대로 넣기 완료
--> 뮤직테이블에 삽입해야 할 값들 삽입 완료
