### ISSUE TITLE
How about changing 'bind' to 'Arrow function'?

### ISSUE THREAD

**Issue by nayunhwan** [YAPP13-4/semi-basement#67]
Hi, I'm Yunhwan, the developer member in Yapp
I have a question after seeing your **React** code.

I saw this line.

https://github.com/YAPP13-4/semi-basement/blob/0f14b194b131b46a89707056d60fb3a7dca3e626/front/src/App/components/Slider.js#L26

It looks to me not efficient that using `bind` each function. I think that If you change `bind` to `Arrow function` like `onClick = (e) => { ... }`, you can get the more high-quality code and improve readability.

This article will help you to improve your code.

https://blueshw.github.io/2017/07/01/arrow-function/

Happy Coding :) 👍

**Comment by nayunhwan** [comment]
If you have a reason about using `bind` instead of `Arrow function`, please explain the reason to me. I think that this communication helps us.

**Comment by SoYoung210** [comment]
Thank you for the remark.. 
I am aware that at some places I bind `this` to my class methods
and in some places I use the arrow function. This is a problem that I have to fix...

Although I found out that using babel's class arrow functions has some issues.
https://medium.com/@charpeni/arrow-functions-in-class-properties-might-not-be-as-great-as-we-think-3b3551c440b1

so I am considering using `auto-bind decorators` afterwards.
At the moment I might just use arrows at the moment.

Thank you though!
