### ISSUE TITLE
Do you have reason for using 'Component' instead of 'PureComponent'?

### ISSUE THREAD

**Issue by nayunhwan** [YAPP13-4/semi-basement#68]
Hi, I'm Yunhwan.
I have another question in your code.

https://github.com/YAPP13-4/semi-basement/blob/0f14b194b131b46a89707056d60fb3a7dca3e626/front/src/App/components/Slider.js#L23

I think that usually `PureComponent` is much better than just `Component` in rendering performance when don't customize `shouldComponentUpdate`.

> I recommend reading this article about 'React Component'
> [**Component vs PureComponent in React**](https://www.vobour.com/%EB%A6%AC%EC%95%A1%ED%8A%B8-react-%EC%9D%B4%ED%95%B4-%EA%B8%B0%EC%B4%88-component-vs-purecomp)

The reason for writing these issues is that I just want to communicate about **React** with other React developers. 

If you don't want that no more, tell me. :)

**Comment by SoYoung210** [comment]
@nayunhwan 
Thank you for the second remark!
Sorry for this late reply..I had a school class. 

It seems appropriate to use PureComponent. 
Thanks to your comments, I am able to complete a better Slider. :)
> I read the article you recommended. Thank you!

I also want to communicate with **React** developers!
And, we welcome all the issues and PR that are attached to this project.

I think it would be a good learning experience for me if I could read the code of your team.
If you do not mind, can I find the address of the Team5's Repository?

**Comment by nayunhwan** [comment]
@SoYoung210 

Good 👍
I don't care about the reply that how much fast or slow.

I will be happy If you read our team code. [Link](https://github.com/Yapp-Web5/Druwa-WEB)

We are trying to adopt new [**Duck**](https://github.com/erikras/ducks-modular-redux) redux pattern, so it may be not awesome. It is the first attempt, we are improving continuously.
