### ISSUE TITLE
백엔드 리팩토링

### ISSUE THREAD

**Issue by SkynI25** [YAPP13-4/semi-basement#76]
백엔드 코드를 정리정돈

**Comment by boribap** [comment]
app.js
db_config.json
routes

config
playlist
album
heartlist
etc

**Comment by SkynI25** [comment]
sql 조건문 만들기

(artwork 테이블에서
url을 반환해라
만약
유저테이블에 있는 어느 토큰이라도
이 토큰과
비슷하다면)
