### ISSUE TITLE
onClick 처리방법 

### ISSUE THREAD

**Issue by SoYoung210** [YAPP13-4/semi-basement#92]
https://github.com/YAPP13-4/semi-basement/blob/52925ba08ea4e549a6cf789f28921ad19b0c2834/front/src/App/components/Header/index.js#L43

```jsx
onClick={ this.props.toggleMyplayer}
```
`toggleMyplayer` 는 파라미터가 없기때문에 위와같이 해도 잘 동작하는데 특별히 익명함수로 감싼 이유가 있으신가요 ?
@livelikeabel

**Comment by livelikeabel** [comment]
으흠

**Comment by livelikeabel** [comment]
몰겟어여 제가 왜 그랬는지 ㅋㅋㅋㅋ

**Comment by livelikeabel** [comment]
익명함수 안감싸도 되는데 ㅋㅋㅋㅋ 리팩토링 부탁드림다 ㅋㅋ큐

**Comment by SoYoung210** [comment]
@livelikeabel 큐큐 저도 어쩌다 발견한겁니다 ;ㅅ; 제코드가 좀더 고칠게 가득하죠 ㅎ..ㅎ 시간날때마다 고쳐봅시다!
이 이슈는 지금 작업하시는 브랜치에서 commit하고 PR과 함께 Close처리 부탁드릴게염 'ㅅ'
